### ISSUE TITLE
PHP file not minimize is the same ...

### ISSUE THREAD

**Issue by coldev** [hareko/php-application-packer#1]
Thanks 4 this excelent library .. i report a bug.....

PHP file not minimize is the same ... please test my file... thanks..

http://pasted.co/336acd18

https://codeshare.io/5DorNr

**Comment by hareko** [comment]
Thanks for your feedback. 

The files have the same timestamp: 2017-05-09 15:14:04. You got different minimized output from the same source? Please, send the source too.

**Comment by coldev** [comment]
i share 2 files to test ...

thanks .. nice tool...
[download 2  php files](http://www.mediafire.com/file/4a1lqehbzckuad1/production.zip)
